import assert from "node:assert/strict";
import { test } from "node:test";

import { describeCron, extractCron, nextRun, parseCron } from "../src/lib/cron";

test("describeCron renders the shapes gh-aw workflows actually use", () => {
  assert.equal(describeCron("0 9 * * 1"), "Mondays at 09:00 UTC");
  assert.equal(describeCron("30 3 * * *"), "daily at 03:30 UTC");
  assert.equal(describeCron("0 */6 * * *"), "every 6 hours");
  assert.equal(describeCron("15 */6 * * *"), "every 6 hours at :15");
  assert.equal(describeCron("0 * * * *"), "hourly");
  assert.equal(describeCron("*/15 * * * *"), "every 15 minutes");
  assert.equal(describeCron("0 9 1 * *"), "monthly on day 1 at 09:00 UTC");
  assert.equal(describeCron("0 9 * * 1-5"), "weekdays at 09:00 UTC");
  assert.equal(describeCron("0 9 * * 1,4"), "Mondays, Thursdays at 09:00 UTC");
});

test("cron 7 means Sunday, same as 0", () => {
  assert.equal(describeCron("0 9 * * 7"), "Sundays at 09:00 UTC");
  assert.deepEqual(parseCron("0 9 * * 0,7")?.daysOfWeek, [0]);
});

test("an unparseable expression degrades to itself instead of throwing", () => {
  assert.equal(parseCron("@daily"), null);
  assert.equal(describeCron("@daily"), "@daily");
  assert.equal(describeCron("0 9 * *"), "0 9 * *");
  assert.equal(parseCron("0 99 * * *"), null);
  assert.equal(nextRun("nonsense"), null);
});

test("nextRun finds the next UTC fire time, strictly in the future", () => {
  // Wednesday 2026-07-29 10:00 UTC.
  const from = new Date("2026-07-29T10:00:00Z");

  assert.equal(nextRun("0 9 * * 1", from)?.toISOString(), "2026-08-03T09:00:00.000Z");
  assert.equal(nextRun("0 */6 * * *", from)?.toISOString(), "2026-07-29T12:00:00.000Z");
  assert.equal(nextRun("0 9 1 * *", from)?.toISOString(), "2026-08-01T09:00:00.000Z");

  // Exactly on a fire time — the NEXT one, never the current minute.
  assert.equal(
    nextRun("0 10 * * *", new Date("2026-07-29T10:00:00Z"))?.toISOString(),
    "2026-07-30T10:00:00.000Z",
  );
});

test("extractCron pulls the schedule out of a compiled gh-aw lock file", () => {
  const lockYaml = [
    "# This file was generated by gh-aw. DO NOT EDIT.",
    'name: "Gardener: Triage"',
    "on:",
    "  schedule:",
    '    - cron: "0 9 * * 1"',
    "  workflow_dispatch:",
    "jobs:",
    "  triage:",
    "    runs-on: ubuntu-latest",
  ].join("\n");

  assert.equal(extractCron(lockYaml), "0 9 * * 1");
  assert.equal(extractCron("- cron: 0 3 * * * # nightly"), "0 3 * * *");
  assert.equal(extractCron("#     - cron: '0 9 * * 1'"), null);
  assert.equal(extractCron("on:\n  workflow_dispatch:\n"), null);
});
