import assert from "node:assert/strict";
import { test } from "node:test";

import {
  describeCron,
  describeCrons,
  extractCrons,
  nextRun,
  nextRunAcross,
  parseCron,
} from "../src/lib/cron";

test("describeCron renders the shapes gh-aw workflows actually use", () => {
  assert.equal(describeCron("0 9 * * 1"), "Mondays at 09:00 UTC");
  assert.equal(describeCron("30 3 * * *"), "daily at 03:30 UTC");
  assert.equal(describeCron("0 */6 * * *"), "every 6 hours");
  assert.equal(describeCron("15 */6 * * *"), "every 6 hours at :15");
  assert.equal(describeCron("0 * * * *"), "hourly");
  assert.equal(describeCron("*/15 * * * *"), "every 15 minutes");
  assert.equal(describeCron("0 9 1 * *"), "monthly on day 1 at 09:00 UTC");
  assert.equal(describeCron("0 9 * * 1-5"), "weekdays at 09:00 UTC");
  assert.equal(describeCron("0 9 * * 1,4"), "Mondays, Thursdays at 09:00 UTC");
});

test("cron 7 means Sunday, same as 0", () => {
  assert.equal(describeCron("0 9 * * 7"), "Sundays at 09:00 UTC");
  assert.deepEqual(parseCron("0 9 * * 0,7")?.daysOfWeek, [0]);
});

test("an unparseable expression degrades visibly instead of throwing", () => {
  assert.equal(parseCron("@daily"), null);
  assert.equal(describeCron("@daily"), "unrecognized schedule (@daily)");
  assert.equal(describeCron("0 9 * *"), "unrecognized schedule (0 9 * *)");
  assert.equal(parseCron("0 99 * * *"), null);
  assert.equal(nextRun("nonsense"), null);
});

test("malformed ranges are rejected, not coerced into a plausible schedule", () => {
  // `Number("")` is 0, so a naive parse reads "-5" as the range 0-5 and
  // renders a confident wrong sentence. Both must degrade instead.
  assert.equal(parseCron("-5 * * * *"), null);
  assert.equal(describeCron("-5 * * * *"), "unrecognized schedule (-5 * * * *)");
  // A three-bound range must not silently drop its third bound.
  assert.equal(parseCron("0 9 * * 1-5-7"), null);
  assert.equal(parseCron("0 9 * * 5-"), null);
  assert.equal(parseCron("0 9 * * -"), null);
  // Number() is generous in other ways too; the field parse must not be.
  assert.equal(parseCron("0x10 9 * * *"), null);
  assert.equal(parseCron("1e1 9 * * *"), null);
  assert.equal(parseCron("+3 9 * * *"), null);
  assert.equal(parseCron("0 9 * * */2/3"), null);
});

test("stepped windows read as windows, not as an exhaustive list of times", () => {
  // Business-hours polling is an ordinary cadence and used to render 18 stamps.
  assert.equal(describeCron("*/30 9-17 * * 1-5"), "weekdays every 30 min 09:00–17:30 UTC");
  assert.equal(describeCron("0 1-23/2 * * *"), "daily every 2h 01:00–23:00 UTC");
});

test("an unsummarizable list of times is capped rather than dumped in full", () => {
  const rendered = describeCron("0,15 9,12,15,18 * * *");
  assert.match(rendered, /UTC, \+4 more$/);
  assert.ok(rendered.length < 70, `too long for a phone cell: ${rendered}`);
});

test("nextRun finds the next UTC fire time, strictly in the future", () => {
  // Wednesday 2026-07-29 10:00 UTC.
  const from = new Date("2026-07-29T10:00:00Z");

  assert.equal(nextRun("0 9 * * 1", from)?.toISOString(), "2026-08-03T09:00:00.000Z");
  assert.equal(nextRun("0 */6 * * *", from)?.toISOString(), "2026-07-29T12:00:00.000Z");
  assert.equal(nextRun("0 9 1 * *", from)?.toISOString(), "2026-08-01T09:00:00.000Z");

  // Exactly on a fire time — the NEXT one, never the current minute.
  assert.equal(
    nextRun("0 10 * * *", new Date("2026-07-29T10:00:00Z"))?.toISOString(),
    "2026-07-30T10:00:00.000Z",
  );
});

test("extractCrons pulls the schedule out of a compiled gh-aw lock file", () => {
  const lockYaml = [
    "# This file was generated by gh-aw. DO NOT EDIT.",
    'name: "Gardener: Triage"',
    "on:",
    "  schedule:",
    '    - cron: "0 9 * * 1"',
    "  workflow_dispatch:",
    "jobs:",
    "  triage:",
    "    runs-on: ubuntu-latest",
  ].join("\n");

  assert.deepEqual(extractCrons(lockYaml), ["0 9 * * 1"]);
  assert.deepEqual(extractCrons("schedule:\n  - cron: 0 3 * * * # nightly"), ["0 3 * * *"]);
  assert.deepEqual(extractCrons("schedule:\n  #  - cron: '0 9 * * 1'"), []);
  assert.deepEqual(extractCrons("on:\n  workflow_dispatch:\n"), []);
});

test("a cron mentioned outside the schedule block is not mistaken for one", () => {
  // Compiled lock files embed the agent prompt inside `run:` blocks, and a
  // maintenance gardener that reasons about schedules will contain cron text.
  const lockYaml = [
    "jobs:",
    "  agent:",
    "    steps:",
    "      - run: |",
    "          Review the workflow whose cron: 0 0 * * * looks wrong.",
    "on:",
    "  schedule:",
    '    - cron: "0 9 * * 1"',
  ].join("\n");

  assert.deepEqual(extractCrons(lockYaml), ["0 9 * * 1"]);
});

test("every schedule entry is collected, and nextRun takes the soonest", () => {
  const lockYaml = [
    "on:",
    "  schedule:",
    "    - cron: '0 9 * * 1'",
    "    - cron: '0 21 * * 4'",
    "  workflow_dispatch:",
  ].join("\n");

  const crons = extractCrons(lockYaml);
  assert.deepEqual(crons, ["0 9 * * 1", "0 21 * * 4"]);
  assert.equal(describeCrons(crons), "Mondays at 09:00 UTC; Thursdays at 21:00 UTC");

  // Wednesday — Thursday's fire is sooner than Monday's, so a first-only
  // parse would have pointed "next in Nd" past a run that really happens.
  const from = new Date("2026-07-29T10:00:00Z");
  assert.equal(nextRunAcross(crons, from)?.toISOString(), "2026-07-30T21:00:00.000Z");
  assert.equal(describeCrons([]), "manual / event-driven");
  assert.equal(nextRunAcross([], from), null);
});
