"use strict";

/**
 * The generated `expo-target.config.js`.
 *
 * The one thing worth asserting is the App Group. `@bacons/apple-targets`
 * mirrors the app's array into targets that can use App Groups, and lets a
 * target override it — which means a wrong override is *silent*: the target
 * builds, installs and runs, and reads a different shared container than the
 * app writes. So the group is written explicitly into every target and checked
 * against the app's here.
 *
 * ## Sabotage record
 *
 *   the explicit App Group dropped in favour of the plugin's mirroring   3 failures
 *   the undefined-key prune removed                                      1 failure
 *
 * The second sabotage first reported **0 failures**: `JSON.stringify` drops an
 * undefined value on its own, so the rendered text was identical either way and
 * only the object a caller inspects had changed. The check below was added to
 * assert that object, and the sabotage then failed once. Recorded because the
 * first run is the useful part — a rendered-output assertion looked like it
 * covered a property it never touched.
 */

const test = require("node:test");
const assert = require("node:assert/strict");
const {
  APP_GROUPS_KEY,
  appGroupIdentifier,
  defineWatchTarget,
  defineWatchWidgetTarget,
  defineWidgetTarget,
  renderTargetConfig,
  withAppleTargets,
} = require("../src/index.js");

const appGroup = appGroupIdentifier("com.example.app");

test("every target kind carries the App Group explicitly", () => {
  for (const [name, define] of [
    ["watch", defineWatchTarget],
    ["widget", defineWidgetTarget],
    ["watch-widget", defineWatchWidgetTarget],
  ]) {
    const target = define({ appGroup });
    assert.equal(target.type, name);
    assert.deepEqual(target.entitlements[APP_GROUPS_KEY], [appGroup], name);
  }
});

test("THE TARGET'S GROUP IS THE ONE THE APP DECLARES", () => {
  const app = withAppleTargets(
    { ios: { bundleIdentifier: "com.example.app" } },
    { appGroup, appleTeamId: "TESTTEAM00" },
  );
  const target = defineWatchTarget({ appGroup });
  assert.deepEqual(target.entitlements[APP_GROUPS_KEY], app.ios.entitlements[APP_GROUPS_KEY]);
});

test("a target without an App Group is refused rather than silently isolated", () => {
  assert.throws(() => defineWatchTarget({}), /needs an appGroup/);
  assert.throws(() => defineWidgetTarget(), /needs an appGroup/);
});

test("watch targets come with sensible frameworks and a deployment target", () => {
  const watch = defineWatchTarget({ appGroup });
  assert.equal(watch.deploymentTarget, "11.0");
  assert.deepEqual(watch.frameworks, ["SwiftUI", "WatchConnectivity"]);
  // ActivityKit belongs to the widget extension, not the watch app.
  assert.deepEqual(defineWidgetTarget({ appGroup }).frameworks, ["SwiftUI", "WidgetKit", "ActivityKit"]);
});

test("every documented key can be set, and overrides the default", () => {
  const target = defineWatchTarget({
    appGroup,
    name: "watch",
    displayName: "Example Watch",
    bundleIdentifier: ".watch",
    deploymentTarget: "10.0",
    icon: "../../assets/watch-icon.png",
    frameworks: ["SwiftUI"],
    entitlements: { "com.apple.developer.healthkit": true },
  });
  assert.equal(target.displayName, "Example Watch");
  assert.equal(target.bundleIdentifier, ".watch");
  assert.equal(target.deploymentTarget, "10.0");
  assert.deepEqual(target.frameworks, ["SwiftUI"]);
  assert.equal(target.entitlements["com.apple.developer.healthkit"], true);
  assert.deepEqual(target.entitlements[APP_GROUPS_KEY], [appGroup], "but never the App Group");
});

test("a key nobody set is absent rather than present-and-undefined", () => {
  // `JSON.stringify` would drop an undefined value anyway, so this is about the
  // object a caller inspects: `"icon" in target` must answer the question
  // "did anyone decide on an icon", which `icon: undefined` does not.
  const target = defineWatchTarget({ appGroup });
  assert.equal("icon" in target, false);
  assert.equal("displayName" in target, false);
  assert.equal("bundleIdentifier" in target, false);
  assert.equal("colors" in target, false);
  assert.equal("type" in target, true);
});

test("the rendered file has no undefined keys in it", () => {
  const rendered = renderTargetConfig(defineWatchTarget({ appGroup }), "Generated by @supa-media/apple-targets.");
  assert.equal(rendered.includes("undefined"), false);
  assert.match(rendered, /^\/\*\* Generated by @supa-media\/apple-targets\. \*\/$/m);
  assert.match(rendered, /module\.exports = \{/);
  assert.match(rendered, /"type": "watch"/);
  // It has to be loadable as CommonJS, because that is how the plugin reads it.
  assert.doesNotThrow(() => new Function("module", "exports", rendered)({ exports: {} }, {}));
});
